config/routes.rb
Rails.application.routes.draw do
  get 'static_people/home'
  get 'static_people/about'
  root "static_people#home"

  get "/about", to: "static_people#about"
  resources :people do
  resources :notes 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :notes, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    person = Person.find(params[:person_id])
    @notes = person.notes.all
  end

  private
    def note_params
      params.require(:note).permit(:body, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
  @person = Person.new(people_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit 
    @person = Person.find(params[:id])
  end
  
  def update
    @person = Person.find(params[:id])

      if @person.update(people_params)
        redirect_to people_path
      else
        render :edit
      end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  

  private
  def people_params
    params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender)
  end  
end

app/controllers/static_people_controller.rb
class StaticPeopleController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_people_helper.rb
module StaticPeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
<%= link_to "About", about_path %>
<%= link_to "People", people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1>Notes</h1>
  <% @notes.each do |note|%>
  <h2>Body: <%= "#{note.body}" %></h2>
  <% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>People</h1>
<%# <p>Find me in app/views/people/index.html.erb</p> %>
  <% @people.each do |person| %>
  <h2>Full Name: <%= "#{person.first_name} #{person.last_name}" %></h2>
  <%= link_to "Show Person", person_path(person) %>
  <%= link_to "Add New Person", new_person_path(person) %>
  <%= link_to "Edit Person", edit_person_path(person) %>
  <%= link_to "Destroy Person!!", person, method: :delete %>
  <%# <%= link_to "Notes", note, %> %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%# <p>Find me in app/views/people/new.html.erb</p> %>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>People</h1>
<%# <p>Find me in app/views/people/show.html.erb</p> %>
<h1>Name: <%= " #{@person.full_name}" %></h1>
<h2>Age <%= @person.age %></h2>
<h2>Hair Color: <%= @person.hair_color %></h2>
<h2>Eye Color: <%= @person.eye_color %></h2>
<h3>Gender: <%= @person.gender %></h3>
<%= link_to "Personal Notes", person_notes_path(@person) %>
<%= link_to "Back", people_path %>

app/views/static_people/about.html.erb
<h1>StaticPeople#about</h1>
<p>Find me in app/views/static_people/about.html.erb</p>

app/views/static_people/home.html.erb
<h1>StaticPeople#home</h1>
<p>Find me in app/views/static_people/home.html.erb</p>